library(dataset)
library(ggplot2)
en=read.csv("energygneration.csv")
df=as.data.frame(en)
data(en)
summary(df)
View(df)
#################################################################################
g <- ggplot(df, aes(producertype,generation))
g + geom_boxplot(varwidth=T, fill="red") + 
  labs(title="Box plot", 
       subtitle="Energy Generated by the top 3 producers in 2017",
       caption="Source: census2011",
       x="Producer Type",
       y="Generation in MGH")



############################################################################
ggplot(df, aes(x=state, y=generation)) + 
  geom_bar(stat="identity", width=.5, fill="tomato3") + 
  labs(title="Ordered Bar Chart", 
       subtitle="State vs Generation") + 
  theme(axis.text.x = element_text(angle=90, vjust=0.6))


brary(ggplot2)
library(plotly)
library(gapminder)
###############################################################

# install package
install.packages('gapminder')

# load library
library(gapminder)

# peek at data
head(gapminder)
111111111111111111111111111111111111111
library(ggplot2)
library(plotly)
library(gapminder)

p <- df %>%
  filter(year==1977) %>%
  ggplot( aes(gdpPercap, lifeExp, size = pop, color=continent)) +
  geom_point() +
  scale_x_log10() +
  theme_bw()

ggplotly(p)
######################################################
l<-ggplot(df, aes(x=year, y=energysource, group=supp)) +
  geom_line(aes(color=supp))+
  geom_point(aes(color=supp))
l
